// context_data.js
const CONTEXT_DATA = {
  "age": "Please write down your age on the form. (Будь ласка, напишіть свій вік у формі.)",
  "citizenship": "She is applying for dual citizenship. (Вона подає документи на подвійне громадянство.)",
  "date of birth": "Enter your date of birth in the format DD/MM/YYYY. (Введіть вашу дату народження у форматі ДД/ММ/РРРР.)",
  "email address": "Could you please provide your email address? (Чи могли б ви надати свою адресу електронної пошти?)",
  "first name": "What is your first name? — My name is Anna. (Яке твоє імя? — Мене звати Анна.)",
  "male": "Please select either male or female. (Будь ласка, виберіть чоловічу або жіночу стать.)",
  "female": "The form indicates whether the applicant is male or female. (Форма вказує, чи є заявник чоловічої чи жіночої статі.)",
  "marital status: single": "State your marital status: single, married, or divorced. (Вкажіть свій сімейний стан: неодружений/незаміжня, одружений/заміжня чи розлучений/розлучена.)",
  "marital status: married": "They have been of married marital status for five years. (Вони перебувають у шлюбі вже пять років.)",
  "marital status: separated": "Although they are not divorced yet, their marital status is separated. (Хоча вони ще не розлучені, їхній сімейний стан — проживають окремо.)",
  "marital status: divorced": "Her marital status changed to divorced last year. (Її сімейний стан змінився на розлучена минулого року.)",
  "marital status: widowed": "He has been of widowed marital status since 2018. (Він є вдівцем із 2018 року.)",
  "name": "What is your full name? (Яке ваше повне імя?)",
  "surname": "Please spell your surname for me. (Будь ласка, вимовте ваше прізвище по літерах.)",
  "nationality": "People of many different nationalities live here. (Тут живуть люди багатьох різних національностей.)",
  "permanent address": "Please provide your permanent address. (Будь ласка, надайте вашу постійну адресу.)",
  "temporary address": "While studying abroad, she used a temporary address. (Під час навчання за кордоном вона використовувала тимчасову адресу.)",
  "place of birth": "Kyiv is listed as his place of birth. (Київ вказаний як його місце народження.)",
  "place of residence": "Change of place of residence must be reported. (Про зміну місця проживання необхідно повідомити.)",
  "telephone number": "Do you have a contact telephone number? (У вас є контактний номер телефону?)",
  "a bald man": "A bald man walked into the shop. (Лисий чоловік зайшов до магазину.)",
  "a beautiful lady": "A beautiful lady smiled at the children. (Прекрасна леді посміхнулася дітям.)",
  "a pretty girl": "She is a pretty girl with a bright smile. (Вона гарна дівчина з яскравою усмішкою.)",
  "fair complexion": "People with fair complexion should use sunscreen. (Людям зі світлим обличчям слід користуватися сонцезахисним кремом.)",
  "dark complexion": "He has a dark complexion from working under the sun. (У нього темне обличчя від роботи під сонцем.)",
  "pale complexion": "Her pale complexion suggested she might be ill. (Її бліде обличчя вказувало на те, що вона може бути хворою.)",
  "tanned complexion": "She returned with a lovely tanned complexion. (Вона повернулася з гарним засмаглим обличчям.)",
  "a girl with freckles": "A cheerful girl with freckles was playing outside. (Весела дівчина з веснянками гралася на вулиці.)",
  "a good-looking woman": "She is a good-looking woman with great style. (Вона красива на вигляд жінка з чудовим стилем.)",
  "an attractive woman": "He found her to be an attractive and intelligent woman. (Він вважав її привабливою та розумною жінкою.)",
  "an ordinary-looking woman": "She is an ordinary-looking woman who values comfort. (Вона звичайна на вигляд жінка, яка цінує комфорт.)",
  "a handsome man": "He is a tall and handsome man. (Він високий та гарний чоловік.)",
  "a well-built man": "A well-built man easily lifted the heavy box. (Чоловік із гарною статурою легко підняв важку коробку.)",
  "a man with a beard and a moustache": "I saw a man with a beard and a moustache. (Я бачив чоловіка з бородою та вусами.)",
  "a middle-aged person": "The seminar is designed for any middle-aged person. (Семінар розрахований на будь-яку людину середнього віку.)",
  "a slim girl": "A slim girl danced gracefully on the stage. (Струнка дівчина граціозно танцювала на сцені.)",
  "a skinny girl": "She looked like a skinny girl during her teenage years. (У підлітковому віці вона виглядала худою дівчиною.)",
  "a thin girl": "A thin girl walked fast against the cold wind. (Схудла дівчина швидко йшла проти холодного вітру.)",
  "a tall man": "A tall man reached the top shelf effortlessly. (Високий чоловік без зусиль дістав до верхньої полиці.)",
  "a short man": "The short man smiled warmly at the guests. (Низький чоловік тепло посміхнувся гостям.)",
  "a woman of average height": "She is a woman of average height and athletic build. (Вона жінка середнього зросту та спортивної статури.)",
  "a woman of medium height": "A woman of medium height entered the room. (Жінка середнього зросту зайшла до кімнати.)",
  "an elderly person": "Please help an elderly person cross the street. (Будь ласка, допоможіть літній людині перейти дорогу.)",
  "blond": "He is a tall, blond young man. (Він високий білявий молодий чоловік.)",
  "blonde": "The blonde woman spoke fluent English. (Блондинка вільно розмовляла англійською.)",
  "chubby": "The baby has chubby cheeks. (У малюка пухкі щічки.)",
  "brown eyes": "She has expressive brown eyes. (У неї виразні карі очі.)",
  "blue eyes": "His blue eyes shone in the sun. (Його блакитні очі сяяли на сонці.)",
  "green eyes": "Cats often have bright green eyes. (Котки часто мають яскраво-зелені очі.)",
  "hazel eyes": "She has beautiful hazel eyes. (У неї красиві карі очі.)",
  "round face": "She has a round face and a sweet smile. (У неї кругле обличчя та мила усмішка.)",
  "oval face": "An oval face is considered very versatile for hairstyles. (Овальне обличчя вважається дуже універсальним для зачісок.)",
  "long face": "He has a long face and high cheekbones. (У нього витягнуте обличчя та високі вилиці.)",
  "thin face": "After the illness, he had a thin face. (Після хвороби у нього було схудле обличчя.)",
  "dark hair": "She prefers keeping her dark hair short. (Вона вважає за краще тримати своє темне волосся коротким.)",
  "fair hair": "Children often have fair hair that darkens with age. (Діти часто мають світле волосся, яке темніє з віком.)",
  "red hair": "He stands out in the crowd with his red hair. (Він виділяється в натовпі своїм рудим волоссям.)",
  "grey hair": "Grandpa has distinguished grey hair. (У дідуся гарне сиве волосся.)",
  "short hair": "Short hair is very easy to maintain in summer. (Коротке волосся дуже легко доглядати влітку.)",
  "long hair": "She brushed her long hair carefully. (Вона ретельно розчесала своє довге волосся.)",
  "straight hair": "She used an iron to make her straight hair even smoother. (Вона використала праску, щоб зробити своє пряме волосся ще гладкішим.)",
  "curly hair": "Curly hair requires special moisturizing care. (Кучеряве волосся вимагає особливого зволожуючого догляду.)",
  "wavy hair": "Her wavy hair fell softly over her shoulders. (Її хвилясте волосся мяко спадало на плечі.)",
  "spiky hair": "He styled his hair into spiky hair with gel. (Він зафіксував волосся гелем, зробивши його стирчатим.)",
  "cropped hair": "He got a cropped hair look for the summer heat. (Він зробив коротку стрижку через літню спеку.)",
  "shoulder length hair": "She likes wearing her shoulder length hair loose. (Вона любить носити своє волосся до плечей розпущеним.)",
  "medium-length hair": "Medium-length hair gives you many styling options. (Волосся середньої довжини дає багато варіантів для зачісок.)",
  "in his early 20s": "He started his first company in his early 20s. (Він заснував свою першу компанію у віці трохи за 20.)",
  "in his mid 20s": "He got married in his mid 20s. (Він одружився у віці близько 25 років.)",
  "in his late 20s": "He finished his PhD in his late 20s. (Він захистив кандидатську дисертацію наприкінці своїх 20-х років.)",
  "in her early 30s": "She bought her apartment in her early 30s. (Вона купила квартиру у віці трохи за 30.)",
  "in her mid 30s": "She wrote her best book in her mid 30s. (Вона написала свою найкращу книгу у віці близько 35 років.)",
  "in her late 30s": "She changed her career path in her late 30s. (Вона змінила карєрний шлях наприкінці своїх 30-х років.)",
  "big nose": "He has a big nose and a sharp gaze. (У нього великий ніс та пронизливий погляд.)",
  "small nose": "She has a cute small nose. (У неї милий маленький ніс.)",
  "long nose": "He inherited a long nose from his grandfather. (Він успадкував довгий ніс від дідуся.)",
  "snub nose": "The baby looked adorable with his snub nose. (Дитина виглядала чарівно зі своїм кирпатим носом.)",
  "pointed nose": "She wore glasses that suited her pointed nose. (Вона носила окуляри, які пасували до її загостреного носа.)",
  "old": "This old house has a lot of history. (Цей старий будинок має багато історії.)",
  "overweight": "The doctor advised him if he is overweight to change his diet. (Лікар порадив йому змінити раціон, якщо він має зайву вагу.)",
  "teenager": "Every teenager faces unique challenges. (Кожен підліток стикається з унікальними викликами.)",
  "toddler": "A curious toddler was exploring the room. (Допитливий малюк досліджував кімнату.)",
  "young": "He is a young and ambitious engineer. (Він молодий та амбітний інженер.)",
  "younger than he looks": "He acts mature, but he is actually younger than he looks. (Він поводиться зріло, але насправді він молодший, ніж на вигляд.)",
  "older than he looks": "Because of his beard, he looks older than his age. (Через бороду він виглядає старшим, ніж є насправді.)",
  "active": "She leads an active lifestyle. (Вона веде активний спосіб життя.)",
  "adventurous": "An adventurous traveler explored the jungle. (Відчайдушний мандрівник досліджував джунглі.)",
  "aggressive": "Avoid aggressive behavior in negotiations. (Уникайте агресивної поведінки на переговорах.)",
  "ambitious": "He has ambitious goals for his career. (У нього амбітні цілі щодо карєри.)",
  "boring": "The lecture was so boring that many students fell asleep. (Лекція була настільки нудною, що багато студентів заснули.)",
  "brave": "The brave firefighter saved the cat. (Хоробрий пожежник врятував кота.)",
  "calm": "Try to stay calm during the crisis. (Намагайтеся залишатися спокійними під час кризи.)",
  "relaxed": "He looked completely relaxed on vacation. (Він виглядав повністю розслабленим на відпочинку.)",
  "caring": "She is a caring mother and wife. (Вона турботлива мати і дружина.)",
  "cheerful": "His cheerful personality brightened up the room. (Його весела особистість прикрасила кімнату.)",
  "clever": "That was a clever solution to the problem. (Це було розумне рішення проблеми.)",
  "confident": "She felt confident before the presentation. (Вона почувалася впевнено перед презентацією.)",
  "consistent": "Be consistent in your daily habits. (Будьте послідовними у своїх повсякденних звичках.)",
  "creative": "Designers need to be very creative. (Дизайнерам потрібно бути дуже творчими.)",
  "easy-going": "He is an easy-going person who gets along with everyone. (Він безтурботна людина, яка з усіма ладнає.)",
  "flexible": "We need a flexible schedule this week. (Нам потрібен гнучкий графік цього тижня.)",
  "forgetful": "Being forgetful, he always writes notes. (Будучи забудькуватим, він завжди робить нотатки.)",
  "friendly": "The local staff was very friendly. (Місцевий персонал був дуже доброзичливим.)",
  "funny": "He told a really funny joke. (Він розповів справді смішний жарт.)",
  "generous": "Thank you for your generous donation. (Дякую за вашу щедру пожертву.)",
  "have a sense of humour": "It is great to have a sense of humour in difficult times. (Чудово мати почуття гумору у важкі часи.)",
  "hard-working": "She is a hard-working student. (Вона працьовита студентка.)",
  "helpful": "Thank you for your helpful advice. (Дякую за вашу корисну пораду.)",
  "honest": "Always be honest with your friends. (Завжди будьте чесними з друзями.)",
  "dishonest": "Dishonest practices will ruin the business. (Нечесні методи зруйнують бізнес.)",
  "indecisive": "He was indecisive about which menu item to choose. (Він не міг вирішити, який пункт меню обрати.)",
  "independent": "She values her independent lifestyle. (Вона цінує свій незалежний спосіб життя.)",
  "jealous": "He felt jealous of his colleague s success. (Він відчув ревнощі через успіх колеги.)",
  "kind": "Be kind to animals. (Будьте добрими до тварин.)",
  "lazy": "Don t be lazy on your path to success. (Не будь ледачим на шляху до успіху.)",
  "mean": "It was mean of him to say that. (Це було підло з його боку — казати таке.)",
  "messy": "His room is always messy. (У його кімнаті завжди безлад.)",
  "moody": "Today she is a bit moody. (Сьогодні вона трохи похмура.)",
  "patient": "Please be patient while we process your request. (Будь ласка, будьте терплячими, поки ми обробляємо ваш запит.)",
  "impatient": "The impatient driver honked his horn. (Нетерплячий водій почав сигналіти.)",
  "polite": "Always remain polite in customer service. (Завжди залишайтеся ввічливими у сфері обслуговування клієнтів.)",
  "impolite": "It is impolite to interrupt others. (Неввічливо перебивати інших.)",
  "punctual": "German trains are known for being punctual. (Німецькі потяги відомі своєю пунктуальністю.)",
  "reasonable": "That is a reasonable price for this service. (Це розважлива ціна за цю послугу.)",
  "rebellious": "Teenagers often go through a rebellious phase. (Підлітки часто проходять через непокірну фазу.)",
  "reliable": "He is a reliable business partner. (Він надійний бізнес-партнер.)",
  "reserved": "She is quiet and somewhat reserved in public. (Вона тиха і дещо замкнена на публіці.)",
  "responsible": "He is responsible for managing the project. (Він відповідальний за управління проєктом.)",
  "irresponsible": "It was irresponsible to leave the door unlocked. (Було безвідповідально залишати двері відчиненими.)",
  "rude": "There is no need to be rude. (Немає потреби бути грубим.)",
  "self-confident": "A self-confident speaker captures the audience attention. (Впевнений у собі оратор привертає увагу аудиторії.)",
  "selfish": "It is selfish to think only of yourself. (Бути егоїстичним і думати лише про себе — неправильно.)",
  "sensitive": "She has sensitive skin. (У неї чутлива шкіра.)",
  "serious": "We need to have a serious conversation. (Нам потрібно провести серйозну розмову.)",
  "shy": "He was too shy to speak in public. (Він був надто сором язливим, щоб говорити публічно.)",
  "sociable": "She is a very sociable person. (Вона дуже товариська людина.)",
  "spoilt": "The child acted like a spoilt brat. (Дитина поводилася як розбещене маля.)",
  "sporty": "He wears sporty clothes on weekends. (Він носить спортивний одяг вихідними.)",
  "strict": "Our teacher has strict rules. (У нашого вчителя суворі правила.)",
  "stubborn": "He is too stubborn to change his mind. (Він занадто впертий, щоб змінити свою думку.)",
  "talented": "She is a talented musician. (Вона талановита музикантка.)",
  "talkative": "He is very talkative during breaks. (Він дуже балакучий під час перерв.)",
  "understanding": "Thank you for being so understanding. (Дякую за те, що ви такі розуміючі.)",
  "unpredictable": "The weather here is completely unpredictable. (Погода тут абсолютно непередбачувана.)",
  "unreliable": "That old car is completely unreliable. (Те старе авто абсолютно ненадійне.)",
  "appropriate for the occasion": "Wear clothes appropriate for the occasion. (Одягайте одяг, відповідний до нагоди.)",
  "baseball cap": "He wore a baseball cap to block the sun. (Він одягнув бейсбольну кепку, щоб захиститися від сонця.)",
  "belt": "He tightened his leather belt. (Він затягнув свій шкіряний ремінь.)",
  "blouse": "She bought a silk blouse. (Вона купила шовкову блузку.)",
  "boots": "Put on your winter boots. (Взуйте зимові чоботи.)",
  "bracelet": "She wore a golden bracelet on her wrist. (Вона носила золотий браслет на зап ясті.)",
  "braces": "He wore braces to straighten his teeth. (Він носив брекети, щоб вирівняти зуби.)",
  "cap": "He took off his cap when entering the house. (Він зняв кепку, входячи в будинок.)",
  "cardigan": "It is chilly, put on a cardigan. (Прохолодно, одягни кардиган.)",
  "coat": "She bought a warm winter coat. (Вона купила тепле зимове пальто.)",
  "jacket": "Take a jacket in case it gets cold. (Візьми куртку на випадок похолодання.)",
  "designer clothes": "She prefers wearing designer clothes. (Вона віддає перевагу дизайнерському одягу.)",
  "expensive clothes": "He spends a lot of money on expensive clothes. (Він витрачає багато грошей на дорогий одяг.)",
  "second-hand clothes": "Shopping for second-hand clothes is eco-friendly. (Купівля вживаного одягу є екологічною.)",
  "earring": "She lost one diamond earring. (Вона загубила одну діамантову сережку.)",
  "evening dress": "She wore an elegant evening dress to the gala. (Вона одягла елегантну вечірню сукню на гала-концерт.)",
  "everyday (casual)": "Keep everyday clothes comfortable. (Зробіть повсякденний одяг зручним.)",
  "comfortable": "Choose comfortable clothes for the trip. (Оберіть зручний одяг для поїздки.)",
  "flip-flops": "He wore flip-flops at the pool. (Він взув в єтнамки біля басейну.)",
  "formal": "The dinner requires formal wear. (Вечеря вимагає офіційного одягу.)",
  "smart": "Dress smart for the interview. (Одягніться охайно для співбесіди.)",
  "elegant": "She looked stunning in her elegant outfit. (Вона виглядала приголомшливо у своєму елегантному вбранні.)",
  "gloves": "Don t forget your gloves in winter. (Не забудьте рукавички взимку.)",
  "hat": "He wore a warm wool hat. (Він одягнув теплу вовняну шапку.)",
  "hooded sweatshirt": "She loves wearing a hooded sweatshirt. (Вона любить носити светр з капюшоном.)",
  "jeans": "His jeans are blue. (Його джинси сині.)",
  "jewelry": "She keeps her jewelry safe. (Вона зберігає свої ювелірні прикраси в безпеці.)",
  "necklace": "She wore a pearl necklace. (Вона одягла перлинне намисто.)",
  "overcoat": "He put on his heavy overcoat. (Він одягнув своє важке пальто.)",
  "polo neck": "A black polo neck is a classic item. (Чорний гольф — це класична річ.)",
  "pajamas": "Time to change into pajamas. (Час переодягатися в піжаму.)",
  "ring": "She showed her engagement ring. (Вона показала свою заручальну каблучку.)",
  "sandals": "She wore leather sandals to the beach. (Вона взула шкіряні босоніжки на пляж.)",
  "scarf": "Wrap a warm scarf around your neck. (Замотайте теплий шарф навколо шиї.)",
  "shirt": "He wore a white cotton shirt. (Він одягнув білу бавовняну сорочку.)",
  "shoes": "Clean your shoes before entering. (Почистьте взуття перед тим, як зайти.)",
  "shorts": "It was too hot, so he wore shorts. (Було дуже спекотно, тому він одягнув шорти.)",
  "skirt": "She wore a pleated skirt. (Вона одягнула спідницю в складку.)",
  "socks": "I need a clean pair of socks. (Мені потрібна чиста пара шкарпеток.)",
  "suit": "He wore a dark business suit. (Він був одягнений у темний діловий костюм.)",
  "sweater": "Grandma knitted a warm sweater. (Бабуся зв язала теплий светр.)",
  "jumper": "He put on a thick wool jumper. (Він одягнув товстий вовняний джемпер.)",
  "swimming trunks": "Don t forget your swimming trunks for the pool. (Не забудьте плавки для басейну.)",
  "swimsuit": "She bought a new red swimsuit. (Вона купила новий червоний купальник.)",
  "tie": "He wore a silk tie to match his suit. (Він одягнув шовкову краватку під костюм.)",
  "bow tie": "He wore a tuxedo with a black bow tie. (Він одягнув смокінг із чорним метеликом.)",
  "tights": "She wore warm tights under her skirt. (Вона одягла теплі колготки під спідницю.)",
  "tracksuit": "He goes running in his tracksuit. (Він бігає у спортивному костюмі.)",
  "trainers": "I bought comfortable running trainers. (Я купив зручні бігові кросівки.)",
  "trendy": "She always wears trendy clothes. (Вона завжди носить модний одяг.)",
  "fashionable": "It is fashionable to wear bright colors this season. (Цього сезону модно носити яскраві кольори.)",
  "underwear": "Pack enough underwear for the trip. (Зберіть достатньо білизни для поїздки.)",
  "adore": "I adore spending time with my family. (Я обожнюю проводити час із сімєю.)",
  "admire": "I admire her dedication to work. (Я захоплююся її відданістю роботі.)",
  "angry": "He was angry about the delay. (Він був злий через затримку.)",
  "furious": "She was furious when she heard the news. (Вона була лютою, коли почула новину.)",
  "annoyed": "He felt annoyed by the constant noise. (Він почувався роздратованим через постійний шум.)",
  "bored": "The children got bored during the long lecture. (Дітям стало нудно під час довгої лекції.)",
  "confused": "I was confused by the complex instructions. (Я був розгублений через складні інструкції.)",
  "delighted": "We were delighted with the results. (Ми були в захваті від результатів.)",
  "pleased": "She was pleased with her grades. (Вона була задоволена своїми оцінками.)",
  "depressed": "Bad weather can make some people feel depressed. (Погана погода може змусити декого почуватися пригніченими.)",
  "disappointed": "He was disappointed with the ending of the book. (Він був розчарований кінцівкою книги.)",
  "embarrassed": "She felt embarrassed when she forgot her lines. (Вона зніяковіла, коли забула свої слова.)",
  "excited": "The kids are excited about the trip. (Діти схвильовані перед поїздкою.)",
  "fancy": "They dined at a fancy restaurant. (Вони вечеряли в дорогому ресторані.)",
  "frightened": "The dog was frightened by the storm. (Собака злякався бурі.)",
  "scared": "Are you scared of heights? (Ти боїшся висоти?)",
  "terrified": "She is terrified of spiders. (Вона панічно боїться павуків.)",
  "grateful": "I am grateful for your support. (Я вдячний за вашу підтримку.)",
  "hate": "I hate waking up early on Mondays. (Я ненавиджу прокидатися рано по понеділках.)",
  "irritated": "He grew irritated by the endless questions. (Він почав дратуватися через нескінченні запитання.)",
  "lonely": "Sometimes living alone makes you feel lonely. (Іноді життя наодинці змушує почуватися самотнім.)",
  "nervous": "She was nervous before the interview. (Вона нервувала перед співбесідою.)",
  "respect": "You must earn the respect of others. (Ти повинен заслужити повагу інших.)",
  "sad": "Why are you looking so sad? (Чому ти виглядаєш таким сумним?)",
  "surprised": "We were surprised by the unexpected visit. (Ми були здивовані неочікуваним візитом.)",
  "amazed": "I was amazed by the view. (Я був вражений краєвидом.)",
  "sympathy": "He expressed deep sympathy for their loss. (Він висловив глибоке співчуття через їхню втрату.)",
  "unhappy": "She felt unhappy with her current job. (Вона почувалася нещасною на своїй поточній роботі.)",
  "worried": "He was worried about the test results. (Він хвилювався щодо результатів тесту.)",
  "argue": "There is no point to argue about this. (Немає сенсу сперечатися про це.)",
  "have an argument": "They had a serious argument yesterday. (Вони серйозно посварилися вчора.)",
  "be ashamed of": "You shouldn t be ashamed of your mistakes. (Тобі не слід соромитися своїх помилок.)",
  "be attracted to sb": "He realized he was attracted to her. (Він зрозумів, що вона йому подобається.)",
  "fall in love": "They fell in love at first sight. (Вони закохалися з першого погляду.)",
  "get on well with": "She gets on well with her colleagues. (Вона добре ладнає зі своїми колегами.)",
  "lose one s temper": "Try not to lose your temper in arguments. (Намагайтеся не втрачати самовладання в суперечках.)"
};
